# Generated by Django 6.0.3 on 2026-04-05 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_conge_professeur_and_agent_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='approuve_directeur_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves_directeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conge',
            name='approuve_drh_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves_drh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_approbation_directeur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_approbation_drh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='user_demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conges_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demande en cours'), ('approuve_directeur', 'Approuvé par directeur'), ('approuve_drh', 'Approuvé par DRH'), ('refuse', 'Refusé')], default='demande', max_length=30),
        ),
        migrations.CreateModel(
            name='CommentaireConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_conge', to=settings.AUTH_USER_MODEL)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='absences.conge')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
