# Generated by Django 6.0.3 on 2026-04-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_conge_approuve_directeur_par_conge_approuve_drh_par_and_more'),
        ('enseignants', '0014_alter_secteur_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges', to='enseignants.etablissement'),
        ),
    ]
