# Generated by Django 6.0.3 on 2026-04-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_conge_etablissement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'permissions': [('demander_conge', 'Peut demander un congé')]},
        ),
    ]
