# Generated by Django 6.0.3 on 2026-04-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0006_alter_conge_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'permissions': [('demander_conge', 'Peut demander un congé'), ('commenter_conge', 'Peut commenter une demande de congé'), ('approuver_conge_directeur', 'Peut approuver un congé au niveau directeur'), ('valider_conge_drh', 'Peut valider un congé au niveau DRH')]},
        ),
    ]
