# Generated by Django 6.0.3 on 2026-03-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('type_structure', models.CharField(choices=[('direction', 'Direction'), ('service', 'Service'), ('division', 'Division'), ('section', 'Section')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('structure_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_structures', to='organigramme.structure')),
            ],
        ),
    ]
