# Generated by Django 6.0.3 on 2026-04-01 20:39

from django.db import migrations, models


def migrate_role_codes(apps, schema_editor):
    User = apps.get_model('comptes', 'User')
    role_mapping = {
        'admin_ministere': 'administrateur',
        'chef_direction': 'secretaire_general',
        'chef_service': 'chef_service_drh',
        'agent': 'professeur',
        'rh': 'technicien_drh',
    }

    for old_role, new_role in role_mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)


def reverse_role_codes(apps, schema_editor):
    User = apps.get_model('comptes', 'User')
    role_mapping = {
        'administrateur': 'admin_ministere',
        'secretaire_general': 'chef_direction',
        'chef_service_drh': 'chef_service',
        'professeur': 'agent',
        'technicien_drh': 'rh',
    }

    for new_role, old_role in role_mapping.items():
        User.objects.filter(role=new_role).update(role=old_role)


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_role_codes, reverse_role_codes),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('chef_service_drh', 'Chef service DRH'), ('secretaire_general', 'Secretaire general'), ('chef_cabinet', 'Chef de cabinet'), ('ministre', 'Ministre'), ('technicien_drh', 'Technicien DRH'), ('professeur', 'Professeur')], default='professeur', max_length=50),
        ),
    ]
