# Generated by Django 6.0.3 on 2026-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('directeur_ecole', "Directeur d'ecole"), ('chef_service_drh', 'Chef service DRH'), ('secretaire_general', 'Secretaire general'), ('chef_cabinet', 'Chef de cabinet'), ('ministre', 'Ministre'), ('technicien_drh', 'Technicien DRH'), ('agent', 'Agent'), ('professeur', 'Professeur')], default='professeur', max_length=50),
        ),
    ]
