# Generated by Django 6.0.3 on 2026-04-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('toggle_user_activation', 'Peut activer ou désactiver un utilisateur')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
