# Generated by Django 6.0.3 on 2026-04-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('toggle_user_activation', 'Peut activer ou désactiver un utilisateur'), ('manage_role_permissions', 'Peut gérer les permissions des rôles')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
