# Generated by Django 6.0.3 on 2026-03-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('organisme', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=150)),
                ('participants', models.ManyToManyField(blank=True, related_name='formations', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField()),
                ('fichier', models.FileField(blank=True, upload_to='formations/certificats/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='agents.agent')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='formations.formation')),
            ],
        ),
    ]
