# Generated by Django 6.0.3 on 2026-03-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('organigramme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigramme.structure'),
        ),
        migrations.AddField(
            model_name='agent',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
