# Generated by Django 6.0.3 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_email_agent_photo_agent_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(error_messages={'unique': 'Ce matricule est déjà utilisé.'}, max_length=50, unique=True),
        ),
    ]
