# Generated by Django 6.0.3 on 2026-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ce matricule est déjà utilisé.'}, max_length=50, unique=True),
        ),
    ]
