# Generated by Django 6.0.3 on 2026-03-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ce mail est déjà utilisé.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé.'}, max_length=20, unique=True),
        ),
    ]
