# Generated by Django 6.0.3 on 2026-04-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('directeur', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duree_mois', models.IntegerField(default=12, help_text='Durée en mois')),
                ('nombre_heures_total', models.IntegerField(default=500, help_text="Total d'heures requises")),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='enseignants.etablissement')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['etablissement', 'nom'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('specialite', models.CharField(help_text='Spécialité du professeur', max_length=200)),
                ('statut', models.CharField(choices=[('permanent', 'Permanent'), ('contractuel', 'Contractuel'), ('vacataire', 'Vacataire'), ('autre', 'Autre')], default='contractuel', max_length=50)),
                ('heures_disponibles', models.IntegerField(default=0, help_text='Heures disponibles par mois')),
                ('heures_affectees', models.IntegerField(default=0, help_text='Heures déjà affectées')),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='enseignants.etablissement')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['etablissement', 'nom', 'prenom'],
                'unique_together': {('etablissement', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('semestre', models.IntegerField(help_text='Numéro du semestre')),
                ('nombre_heures', models.IntegerField(default=100, help_text="Nombre d'heures total du programme")),
                ('ordre', models.IntegerField(default=1, help_text="Ordre d'apparition")),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='enseignants.filiere')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['filiere', 'semestre', 'ordre'],
                'unique_together': {('filiere', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('nombre_heures', models.IntegerField(default=20, help_text="Nombre d'heures du module")),
                ('nombre_heures_pratique', models.IntegerField(default=0, help_text='Heures pratiques vs théoriques')),
                ('professeur_requis', models.IntegerField(default=1, help_text='Nombre de professeurs requis')),
                ('ordre', models.IntegerField(default=1, help_text="Ordre d'apparition")),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='enseignants.programme')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['programme', 'ordre'],
                'unique_together': {('programme', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heures', models.IntegerField(help_text='Heures assignées au professeur pour ce module')),
                ('priorite', models.CharField(choices=[('1', 'Critique'), ('2', 'Haute'), ('3', 'Moyenne'), ('4', 'Basse')], default='2', max_length=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='enseignants.module')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='enseignants.professeur')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-priorite', 'professeur', 'module'],
                'unique_together': {('professeur', 'module')},
            },
        ),
    ]
