# Generated by Django 6.0.3 on 2026-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['prefecture', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Préfecture',
                'verbose_name_plural': 'Préfectures',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='professeur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='affectation',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='enseignants.etablissement'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='enseignants.filiere'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='heures_affectees',
            field=models.IntegerField(default=0, help_text='Heures affectées dans cet établissement'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_associees', to='enseignants.programme'),
        ),
        migrations.AddField(
            model_name='module',
            name='duree_heures',
            field=models.IntegerField(default=0, help_text='Durée du module en heures'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='corps',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='professeur',
            name='hierarchie',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AddField(
            model_name='programme',
            name='module_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes_principaux', to='enseignants.module'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='enseignants.commune'),
        ),
        migrations.AddField(
            model_name='commune',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='enseignants.prefecture'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='enseignants.prefecture'),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='enseignants.commune')),
            ],
            options={
                'verbose_name': 'Quartier / District',
                'verbose_name_plural': 'Quartiers / Districts',
                'ordering': ['commune', 'nom'],
                'unique_together': {('commune', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='enseignants.quartier'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='enseignants.region'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='enseignants.region'),
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='enseignants.quartier')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['quartier', 'nom'],
                'unique_together': {('quartier', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='enseignants.secteur'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('prefecture', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='prefecture',
            unique_together={('region', 'nom')},
        ),
    ]
