# Generated by Django 6.0.3 on 2026-04-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0002_commune_prefecture_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
