# Generated by Django 6.0.3 on 2026-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0003_alter_professeur_matricule'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='affectation',
            table='affectation',
        ),
        migrations.AlterModelTable(
            name='commune',
            table='commune',
        ),
        migrations.AlterModelTable(
            name='etablissement',
            table='etablissement',
        ),
        migrations.AlterModelTable(
            name='filiere',
            table='filiere',
        ),
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
        migrations.AlterModelTable(
            name='prefecture',
            table='prefecture',
        ),
        migrations.AlterModelTable(
            name='professeur',
            table='professeur',
        ),
        migrations.AlterModelTable(
            name='programme',
            table='programme',
        ),
        migrations.AlterModelTable(
            name='quartier',
            table='quartier',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='secteur',
            table='secteur',
        ),
    ]
