# Generated by Django 6.0.3 on 2026-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0004_alter_affectation_table_alter_commune_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
