# Generated by Django 6.0.3 on 2026-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0005_alter_etablissement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='directeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
