# Generated by Django 6.0.3 on 2026-04-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0006_alter_etablissement_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='enseignants.programme'),
        ),
    ]
