# Generated by Django 6.0.3 on 2026-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0007_alter_module_programme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['nom', 'ordre'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='programme',
        ),
    ]
