# Generated by Django 6.0.3 on 2026-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0008_alter_module_options_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='nombre_heures_pratique',
        ),
        migrations.RemoveField(
            model_name='module',
            name='professeur_requis',
        ),
    ]
