# Generated by Django 6.0.3 on 2026-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0009_remove_module_nombre_heures_pratique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='duree_heures',
        ),
    ]
