# Generated by Django 6.0.3 on 2026-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0010_remove_module_duree_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
