# Generated by Django 6.0.3 on 2026-04-01 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0011_alter_module_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='statut',
            field=models.CharField(choices=[('permanent', 'Fonctionnaire'), ('contractuel', 'Contractuel'), ('vacataire', 'Vacataire'), ('autre', 'Autre')], default='contractuel', max_length=50),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secteurs', to='enseignants.quartier'),
        ),
    ]
