# Generated by Django 6.0.3 on 2026-04-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0013_make_secteur_quartier_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secteur',
            unique_together=set(),
        ),
    ]
