# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations, models


def copy_legacy_module_to_m2m(apps, schema_editor):
    Programme = apps.get_model('enseignants', 'Programme')
    for programme in Programme.objects.exclude(module_formation_legacy__isnull=True):
        programme.module_formation.add(programme.module_formation_legacy_id)


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0014_alter_secteur_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='module_formation',
            new_name='module_formation_legacy',
        ),
        migrations.AddField(
            model_name='programme',
            name='module_formation',
            field=models.ManyToManyField(blank=True, related_name='programmes_principaux', to='enseignants.module'),
        ),
        migrations.RunPython(copy_legacy_module_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='programme',
            name='module_formation_legacy',
        ),
    ]
