# Generated by Django 6.0.3 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0015_alter_programme_module_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='enseignants.filiere'),
        ),
    ]
