# Generated by Django 6.0.3 on 2026-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0017_remove_affectation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enseignants/photos/'),
        ),
    ]
