# Generated by Django 6.0.3 on 2026-04-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0018_professeur_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filiere',
            name='etablissements',
            field=models.ManyToManyField(blank=True, related_name='filieres_partagees', to='enseignants.etablissement'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='enseignants.etablissement'),
        ),
    ]
