# Generated by Django 6.0.3 on 2026-04-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0020_backfill_and_merge_shared_filieres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['nom', 'ordre'], 'permissions': [('view_besoin', "Peut consulter les besoins d'enseignement"), ('view_besoin_suggestions', 'Peut consulter les suggestions de professeurs pour les besoins'), ('export_csv_template', 'Peut télécharger les modèles CSV'), ('export_csv_data', 'Peut exporter les données CSV'), ('import_csv_data', 'Peut importer des données CSV')], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
