# Generated by Django 6.0.3 on 2026-04-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0021_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['nom', 'ordre'], 'permissions': [('view_besoin', "Peut consulter les besoins d'enseignement"), ('view_besoin_suggestions', 'Peut consulter les suggestions de professeurs pour les besoins'), ('export_csv_template', 'Peut télécharger les modèles CSV'), ('export_csv_data', 'Peut exporter les données CSV'), ('import_csv_data', 'Peut importer des données CSV'), ('access_geo_filters', 'Peut utiliser les filtres géographiques'), ('filter_filieres_by_etablissement', 'Peut filtrer les filières par établissement'), ('filter_modules_by_filiere', 'Peut filtrer les modules par filière'), ('preview_affectation', 'Peut prévisualiser une affectation')], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
