# Generated by Django 6.0.3 on 2026-04-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0022_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={'ordering': ['-priorite', 'professeur', 'module'], 'permissions': [('preview_affectation', 'Peut prévisualiser une affectation')], 'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['prefecture', 'nom'], 'permissions': [('csv_communes', 'Peut importer/exporter des données CSV Communes')], 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['nom'], 'permissions': [('access_geo_filters', 'Peut utiliser les filtres géographiques')], 'verbose_name': 'Établissement', 'verbose_name_plural': 'Établissements'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom'], 'permissions': [('filter_filieres_by_etablissement', 'Peut filtrer les filières par établissement')], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['nom', 'ordre'], 'permissions': [('view_besoin', "Peut consulter les besoins d'enseignement"), ('view_besoin_suggestions', 'Peut consulter les suggestions de professeurs pour les besoins'), ('csv_modules', 'Peut importer/exporter des données CSV Modules'), ('filter_modules_by_filiere', 'Peut filtrer les modules par filière')], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ['region', 'nom'], 'permissions': [('csv_prefectures', 'Peut importer/exporter des données CSV Préfectures')], 'verbose_name': 'Préfecture', 'verbose_name_plural': 'Préfectures'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['filiere', 'semestre', 'ordre'], 'permissions': [('csv_programmes', 'Peut importer/exporter des données CSV Programmes')], 'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AlterModelOptions(
            name='quartier',
            options={'ordering': ['commune', 'nom'], 'permissions': [('csv_quartiers', 'Peut importer/exporter des données CSV Quartiers')], 'verbose_name': 'Quartier / District', 'verbose_name_plural': 'Quartiers / Districts'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom'], 'permissions': [('csv_regions', 'Peut importer/exporter des données CSV Régions')], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterModelOptions(
            name='secteur',
            options={'ordering': ['quartier', 'nom'], 'permissions': [('csv_secteurs', 'Peut importer/exporter des données CSV Secteurs')], 'verbose_name': 'Secteur', 'verbose_name_plural': 'Secteurs'},
        ),
    ]
