# Generated by Django 6.0.3 on 2026-04-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0024_cleanup_old_module_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeur',
            options={'ordering': ['etablissement', 'nom', 'prenom'], 'permissions': [('csv_professeurs', 'Peut importer/exporter des données CSV Professeurs')], 'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
    ]
